export const actionTypes = {
    REPORTS_FETCH_REQUESTED: "REPORTS_FETCH_REQUESTED",
    REPORTS_FETCH_SUCCEEDED: "REPORTS_FETCH_SUCCEEDED",
    REPORTS_FETCH_FAILED: "REPORTS_FETCH_FAILED",

    REPORT_DELETE_REQUESTED: "REPORT_DELETE_REQUESTED",
    REPORT_DELETE_SUCCEEDED: "REPORT_DELETE_SUCCEEDED",
    REPORT_DELETE_FAILED: "REPORT_DELETE_FAILED",

    CANDIDATES_FETCH_REQUESTED: "CANDIDATES_FETCH_REQUESTED",
    CANDIDATES_FETCH_SUCCEEDED: "CANDIDATES_FETCH_SUCCEEDED",
    CANDIDATES_FETCH_FAILED: "CANDIDATES_FETCH_FAILED",

    COMPANIES_FETCH_REQUESTED: "COMPANIES_FETCH_REQUESTED",
    COMPANIES_FETCH_SUCCEEDED: "COMPANIES_FETCH_SUCCEEDED",
    COMPANIES_FETCH_FAILED: "COMPANIES_FETCH_FAILED",

    REPORT_POST_REQUESTED: "REPORT_POST_REQUESTED",
    REPORT_POST_SUCCEEDED: "REPORT_POST_SUCCEEDED",
    REPORT_POST_FAILED: "REPORT_POST_FAILED",

    DATA_FETCH_REQUESTED: "DATA_FETCH_REQUESTED",
    DATA_FETCH_FAILED: "DATA_FETCH_FAILED",
    DATA_FETCH_SUCCEEDED: "DATA_FETCH_SUCCEEDED",

    SET_ACTIVE_MODAL: "SET_ACTIVE_MODAL",
    SET_ACTIVE_WIZARD_TAB: "SET_ACTIVE_WIZARD_TAB",

    CANDIDATE_SELECTED: "CANDIDATE_SELECTED",
    COMPANY_SELECTED: "COMPANY_SELECTED",
    INTERVIEW_DATE_SELECTED: "INTERVIEW_DATE_SELECTED",
    PHASE_SELECTED: "PHASE_SELECTED",
    STATUS_SELECTED: "STATUS_SELECTED",
    NOTES_FILLED_IN: "NOTES_FILLED_IN",
    
    RESET_WIZARD_DATA: "RESET_WIZARD_DATA",
    IS_READY_FOR_POST: "IS_READY_FOR_POST"
}

export const apiEndpoints = {
    baseUrl: "http://localhost:3333/api/",
    reports: "http://localhost:3333/api/reports/",
    candidates: "http://localhost:3333/api/candidates/",
    companies: "http://localhost:3333/api/companies/",
}

export const wizardTabs = {
    CANDIDATE_TAB: "CANDIDATE_TAB",
    COMPANY_TAB: "COMPANY_TAB",
    FILL_DETAILS_TAB: "FILL_DETAILS_TAB"
}

export const placeholder = {
    avatar: "http://fuuse.net/wp-content/uploads/2016/02/avatar-placeholder.png"
}